{
 "title": "Main",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Fast Sheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processing count total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(scheduler_fast_processing_count_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch processing (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(scheduler_fast_batch_processing_time_seconds_bucket{place=\"schedulers\"}[$__rate_interval])))",
     "legendFormat": "99q"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(scheduler_fast_batch_processing_time_seconds_bucket{place=\"schedulers\"}[$__rate_interval])) by (le))",
     "legendFormat": "95q"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(scheduler_fast_batch_processing_time_seconds_bucket{place=\"schedulers\"}[$__rate_interval])) by (le))",
     "legendFormat": "90q"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(scheduler_fast_batch_processing_time_seconds_bucket{place=\"schedulers\"}[$__rate_interval])) by (le))",
     "legendFormat": "75q"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(scheduler_fast_batch_processing_time_seconds_bucket{place=\"schedulers\"}[$__rate_interval])) by (le))",
     "legendFormat": "50q"
    }
   ]
  },
  {
   "title": "Batches total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(scheduler_fast_batches_count_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "executor_pool_core_threads{name=\"taskExecutorForFastStorage\"}",
     "legendFormat": "core_threads"
    },
    {
     "expr": "executor_pool_size_threads{name=\"taskExecutorForFastStorage\"}",
     "legendFormat": "size_threads"
    },
    {
     "expr": "executor_active_threads{name=\"taskExecutorForFastStorage\"}",
     "legendFormat": "active_threads"
    }
   ]
  },
  {
   "title": "Duplicates fetched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(scheduler_fast_duplicates_filtered_count_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Common Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Processing count total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(scheduler_common_processing_count_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch processing (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scheduler_common_batch_processing_time_seconds_bucket{place=\"schedulers\"}[$__rate_interval])) by (le))",
     "legendFormat": "99q"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(scheduler_common_batch_processing_time_seconds_bucket{place=\"schedulers\"}[$__rate_interval])) by (le))",
     "legendFormat": "95q"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(scheduler_common_batch_processing_time_seconds_bucket{place=\"schedulers\"}[$__rate_interval])) by (le))",
     "legendFormat": "90q"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(scheduler_common_batch_processing_time_seconds_bucket{place=\"schedulers\"}[$__rate_interval])) by (le))",
     "legendFormat": "75q"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(scheduler_common_batch_processing_time_seconds_bucket{place=\"schedulers\"}[$__rate_interval])) by (le))",
     "legendFormat": "50q"
    }
   ]
  },
  {
   "title": "Batches total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(scheduler_common_batches_count_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "executor_pool_core_threads{name=\"taskExecutorForFastStorage\"}",
     "legendFormat": "core_threads"
    },
    {
     "expr": "executor_pool_size_threads{name=\"taskExecutorForCommonStorage\"}",
     "legendFormat": "size_threads"
    },
    {
     "expr": "executor_active_threads{name=\"taskExecutorForCommonStorage\"}",
     "legendFormat": "active_threads"
    }
   ]
  },
  {
   "title": "Time Window Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    { "expr": "scheduler_common_window_value", "legendFormat": "__auto" }
   ]
  }
 ]
}