CREATE TABLE Scenario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    text TEXT NOT NULL,
    clientId BIGINT,
    friendIds BIGINT[],
    firstTimeToActivate TIMESTAMP,
    listTimesToActivate TIMESTAMP[],
    allowedDelayAfterPing INT,
    okFromAntispam BOOLEAN,
    textToPing TEXT
);
