CREATE TABLE Scenario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    text TEXT NOT NULL,
    toIds INTEGER[],
    firstTimeToActivate TIMESTAMP,
    listTimesToActivate TIMESTAMP[],
    allowedDelayAfterPing INTERVAL,
    okFromAntispam BOOLEAN,
    textToPing TEXT
);
