CREATE TABLE ChatToBots
(
    chatId BIGINT PRIMARY KEY,
    botId  BIGINT
);

CREATE TABLE Bots
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    url          VARCHAR(255) NOT NULL,
    countOfUsers BIGINT
);

INSERT INTO Bots (name, url, countOfUsers)
VALUES ('T-1', 'stub', 0),
       ('T-2', 'stub', 0),
       ('T-3', 'stub', 0),
       ('T-4', 'stub', 0),
       ('T-5', 'stub', 0);